version: '3'
services:
  master:
    build:
      context: ./master
    ports:
      - "3000:3000"
    networks:
      - my_network

  node1:
    build:
      context: ./node1
    ports:
      - "3001:3000"
    networks:
      - my_network

  node2:
    build:
      context: ./node2
    ports:
      - "3002:3000"
    networks:
      - my_network

  node3:
    build:
      context: ./node3
    ports:
      - "3003:3000"
    networks:
      - my_network

  node4:
    build:
      context: ./node4
    ports:
      - "3004:3000"
    networks:
      - my_network

  node5:
    build:
      context: ./node5
    ports:
      - "3005:3000"
    networks:
      - my_network

networks:
  my_network: